services:
  # Backend API Service
  - type: web
    name: phone-generator-api
    env: java
    region: singapore
    plan: free
    buildCommand: cd backend && ./mvnw clean install -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        value: jdbc:mysql://phonegen-mysql.mysql.database.azure.com:3306/phone_number_generator?useSSL=true&serverTimezone=UTC
      - key: DATABASE_USERNAME
        value: adminuser@phonegen-mysql
      - key: DATABASE_PASSWORD
        value: Password123@
      - key: PORT
        value: 8080
      - key: JAVA_VERSION
        value: 17
    healthCheckPath: /actuator/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: phone-generator-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://phone-generator-api.onrender.com
    staticPublishPath: ./frontend/dist
    autoDeploy: true 