FROM maven:3.9-amazoncorretto-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Add MySQL JDBC driver
RUN apk add --no-cache mysql-client

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"] 